# Generated by Django 3.1.5 on 2021-01-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentairePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=1000, verbose_name='Institution')),
                ('nom', models.CharField(blank=True, max_length=1000, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=1000, verbose_name='Prénom')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000, verbose_name='Nom')),
                ('num_mgg', models.CharField(max_length=1000, unique=True, verbose_name='NUM_MGG')),
                ('num_mjb1', models.CharField(max_length=1000, verbose_name='NUM_MJB1')),
                ('num_mjb2', models.CharField(blank=True, max_length=1000, verbose_name='NUM_MJB2')),
                ('commande', models.BooleanField(null=True, verbose_name='Commande')),
                ('volume', models.CharField(blank=True, choices=[('Ronde-bosse', 'Ronde Bosse'), ('Bas-relief', 'Bas Relief')], max_length=1000, verbose_name='Volume')),
                ('notes_mjb', models.CharField(blank=True, max_length=5000, verbose_name='NotesMJB')),
                ('description', models.CharField(blank=True, max_length=5000, verbose_name='Description')),
                ('dim_hauteur', models.CharField(blank=True, max_length=1000, verbose_name='Dim_Hauteur')),
                ('dim_base', models.CharField(blank=True, max_length=1000, verbose_name='Dim_Base')),
                ('type_original_moulage', models.CharField(blank=True, max_length=1000, verbose_name='TypeOriginalMoulage')),
                ('date_creation', models.DateTimeField(verbose_name='DateCreation')),
                ('date_modification', models.DateTimeField(verbose_name='DateModification')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=1000, unique=True, verbose_name='Matière')),
            ],
        ),
        migrations.CreateModel(
            name='Photographie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=1000, unique=True, verbose_name='numéro_photo')),
                ('qualite', models.CharField(blank=True, max_length=1000, verbose_name='QualitéPhoto')),
                ('orientation', models.CharField(blank=True, choices=[('Portrait', 'Portrait'), ('Paysage', 'Paysage')], max_length=1000, verbose_name='OrientationPhoto')),
                ('nom_fichier', models.CharField(choices=[('Basse Définition (BD)', 'Basse Définition (BD)'), ('Haute Dédinition (HD)', 'Haute Définition (HD)')], max_length=1000, verbose_name='Nom_Fichier_Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_cle', models.CharField(max_length=1000, unique=True, verbose_name='Mot Clé')),
            ],
        ),
        migrations.CreateModel(
            name='RelationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('Artiste', 'Artiste'), ('Propriétaire', 'Proprietaire'), ('Marchand', 'Marchand'), ('Commanditaire', 'Commanditaire'), ('Cireur', 'Cireur'), ('Mouleur', 'Mouleur'), ('Marbrier', 'Marbrier'), ('Fondeur', 'Fondeur')], max_length=1000, verbose_name='EtatContact')),
                ('debut', models.CharField(blank=True, max_length=1000, verbose_name='ContactDateDebut')),
                ('fin', models.CharField(blank=True, max_length=1000, verbose_name='ContactDateFin')),
                ('prix_cession', models.CharField(blank=True, max_length=1000, verbose_name='PrixCession')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mjb.contact')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mjb.inventaire')),
            ],
        ),
        migrations.AddField(
            model_name='inventaire',
            name='contacts',
            field=models.ManyToManyField(through='mjb.RelationContact', to='mjb.Contact'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='inventaire_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mjb.inventaire', verbose_name='lienIDInventaireOriginal'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='matieres',
            field=models.ManyToManyField(blank=True, to='mjb.Matiere', verbose_name='matière'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='photographies',
            field=models.ManyToManyField(through='mjb.CommentairePhoto', to='mjb.Photographie'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='themes',
            field=models.ManyToManyField(blank=True, to='mjb.Theme'),
        ),
        migrations.AddField(
            model_name='commentairephoto',
            name='inventaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mjb.inventaire'),
        ),
        migrations.AddField(
            model_name='commentairephoto',
            name='photographie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mjb.photographie'),
        ),
    ]
