# Generated by Django 3.1.5 on 2021-01-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='inventaire_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='declinaisons', to='mjb.inventaire', verbose_name='lienIDInventaireOriginal'),
        ),
    ]
