# Generated by Django 3.1.5 on 2021-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0002_auto_20210121_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographie',
            name='nom_fichier',
            field=models.CharField(max_length=1000, verbose_name='Nom_Fichier_Photo'),
        ),
        migrations.AlterField(
            model_name='photographie',
            name='qualite',
            field=models.CharField(blank=True, choices=[('Basse Définition (BD)', 'Basse Définition (BD)'), ('Haute Dédinition (HD)', 'Haute Définition (HD)')], max_length=1000, verbose_name='QualitéPhoto'),
        ),
    ]
