# Generated by Django 3.1.5 on 2021-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0003_auto_20210123_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='import_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
