# Generated by Django 3.1.5 on 2021-01-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0005_auto_20210123_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DateCreation'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DateModification'),
        ),
    ]
