# Generated by Django 3.1.5 on 2021-01-23 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0006_auto_20210123_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='DateCreation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='DateModification'),
            preserve_default=False,
        ),
    ]
