# Generated by Django 3.1.5 on 2021-01-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0007_auto_20210123_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventaire',
            name='matieres',
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='themes',
        ),
    ]
