# Generated by Django 3.1.5 on 2021-01-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0008_auto_20210123_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mjb.inventaire')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mjb.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire_Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mjb.inventaire')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mjb.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='inventaire',
            name='matieres',
            field=models.ManyToManyField(blank=True, through='mjb.Inventaire_Matiere', to='mjb.Matiere', verbose_name='matière'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='themes',
            field=models.ManyToManyField(blank=True, through='mjb.Inventaire_Theme', to='mjb.Theme'),
        ),
    ]
