# Generated by Django 3.1.5 on 2021-02-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0010_auto_20210124_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date création fiche'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modification fiche'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='dim_base',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Base (cm)'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='dim_hauteur',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Hauteur (cm)'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='inventaire_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='declinaisons', to='mjb.inventaire', verbose_name='De suite'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='notes_mjb',
            field=models.TextField(blank=True, verbose_name='Notes Marie-Jo'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='num_mgg',
            field=models.CharField(max_length=1000, unique=True, verbose_name="N° d'inventaire"),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='num_mjb1',
            field=models.CharField(blank=True, max_length=1000, verbose_name='N° Marie-Jo'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='num_mjb2',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='type_original_moulage',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Connu/Inconnu/De suite'),
        ),
    ]
