# Generated by Django 3.1.5 on 2021-02-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0013_auto_20210213_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographie',
            name='numero',
            field=models.CharField(blank=True, max_length=1000, verbose_name='numéro_photo'),
        ),
    ]
