# Generated by Django 3.1.5 on 2021-02-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjb', '0015_manual_import_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographie',
            name='image_ok',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photographie',
            name='vignette_ok',
            field=models.BooleanField(null=True),
        ),
    ]
